# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  domain: http://localhost:3000
  unique_key_length: 5
  black_list: 'foo,bar'
  secret_key_base: 504a79a95451c09c12d87e20f7e8585a207152b7f0e765cc74ca545e981e382f85f06f0f5051d293aef91b7b8495f3998ceef43dffbc4f16b19dd9f3d2f4c946

test:
  domain: http://localhost:3000
  unique_key_length: 5
  black_list: 'foo,bar'
  secret_key_base: 58eaf099d76b21993dbc1201fd5e5cc88f41925c57c3432b3271eb59d2b8613a45bcf7f7cf03e1d11765f39f7fd5fabae8f3bee06c3df092bbfe828ebf43c13d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  domain: https://rfrith-shortenurl.herokuapp.com
  unique_key_length: 5
  black_list: 'foo,bar'
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
